name: darksky_weather
description: A dart library for interfacing with the Dark Sky Weather API.
version: 2.0.0
homepage: https://github.com/rinukkusu/darksky-weather-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.4.0
  http: ^0.13.4

dev_dependencies:
  test: ^1.3.0
  json_serializable: ^6.1.1
  build_runner: ^2.1.5

